// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class AuthItem
    {
        public AuthItem()
        {
            AuthAssignment = new HashSet<AuthAssignment>();
            AuthItemChild = new HashSet<AuthItemChild>();
        }

        public string Name { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public string RuleName { get; set; }
        public string Data { get; set; }
        public int? CreatedAt { get; set; }
        public int? UpdatedAt { get; set; }

        public virtual AuthRule RuleNameNavigation { get; set; }
        public virtual ICollection<AuthAssignment> AuthAssignment { get; set; }
        public virtual ICollection<AuthItemChild> AuthItemChild { get; set; }
    }
}