// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class AuthAssignment
    {
        public string ItemName { get; set; }
        public string UserId { get; set; }
        public int? CreatedAt { get; set; }

        public virtual AuthItem ItemNameNavigation { get; set; }
    }
}