// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class AuthRule
    {
        public AuthRule()
        {
            AuthItem = new HashSet<AuthItem>();
        }

        public string Name { get; set; }
        public string Data { get; set; }
        public int? CreatedAt { get; set; }
        public int? UpdatedAt { get; set; }

        public virtual ICollection<AuthItem> AuthItem { get; set; }
    }
}