// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class Boxpage
    {
        public long Id { get; set; }
        public int BoxpageCatId { get; set; }
        public string Name { get; set; }
        public string SubName { get; set; }
        public string Src { get; set; }
        public string Link { get; set; }
        public short Status { get; set; }
        public string Multitext { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public string Language { get; set; }
        public int? IdRelated { get; set; }
    }
}