// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class BoxpageMedia
    {
        public long Id { get; set; }
        public int? BoxpageId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string PathVideo { get; set; }
        public short? Type { get; set; }
        public short? SubType { get; set; }
        public short? IsDefault { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? CreatedAt { get; set; }
    }
}