// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class CitiesDistrict
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public short? Type { get; set; }
        public int ParentId { get; set; }
        public int SortOrder { get; set; }
        public int SortOrderFooter { get; set; }
        public short Status { get; set; }
        public int? CrawlId { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public short IsHome { get; set; }
        public string Alias { get; set; }
    }
}