// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class EmailLetter
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public short? Status { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string Language { get; set; }
    }
}