// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class Log
    {
        public long Id { get; set; }
        public int? Level { get; set; }
        public string Category { get; set; }
        public double? LogTime { get; set; }
        public string Prefix { get; set; }
        public string Message { get; set; }
    }
}