// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class LogAction
    {
        public long Id { get; set; }
        public string Url { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Ip { get; set; }
        public string Module { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}