// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class LogIpLogin
    {
        public long Id { get; set; }
        public string Ip { get; set; }
        public long Vcount { get; set; }
        public string Username { get; set; }
    }
}