// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class LogSubscribeError
    {
        public long Id { get; set; }
        public string Ip { get; set; }
        public int? ErrorCode { get; set; }
        public string Content { get; set; }
        public string ErrMessage { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}