// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class NewsCatRel
    {
        public long NewsId { get; set; }
        public long NewsCatId { get; set; }
        public DateTime? CreatedAt { get; set; }
    }
}