// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class RoutePage
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }
    }
}