// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class SeoPage
    {
        public long Id { get; set; }
        public int RouteId { get; set; }
        public string RouteName { get; set; }
        public string PageTitle { get; set; }
        public string PageKeywords { get; set; }
        public string PageDescription { get; set; }
        public string FaceTitle { get; set; }
        public string FaceImage { get; set; }
        public string FaceDescription { get; set; }
        public string Multitext { get; set; }
        public string Language { get; set; }
        public int? IdRelated { get; set; }
    }
}