// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class SiteContact
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string LinkLogo { get; set; }
        public string LinkLogoFooter { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Hotline { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string LinkFace { get; set; }
        public string LinkInsta { get; set; }
        public string LinkYoutube { get; set; }
        public string LinkTwitter { get; set; }
        public string LinkZalo { get; set; }
        public string LinkMessenger { get; set; }
        public string LinkMap { get; set; }
        public string LinkFavicon { get; set; }
        public string EmbedScriptHead { get; set; }
        public string EmbedScriptBodyBegin { get; set; }
        public string EmbedScriptBodyEnd { get; set; }
        public string Multitext { get; set; }
        public string Language { get; set; }
    }
}