// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class Subscribe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public short? Status { get; set; }
        public string Ip { get; set; }
        public short? Type { get; set; }
        public string UtmCampaign { get; set; }
        public string UtmMedium { get; set; }
        public string UtmContent { get; set; }
        public string UtmSource { get; set; }
        public string UtmTerm { get; set; }
        public string UtmReferrer { get; set; }
        public string Cookies { get; set; }
        public string Note { get; set; }
        public string Phongban { get; set; }
        public int? ObjectId { get; set; }
        public string File { get; set; }
    }
}