// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class Tag
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Tag1 { get; set; }
        public byte Status { get; set; }
        public string PageTitle { get; set; }
        public string PageDescription { get; set; }
        public string TitleSeobox { get; set; }
        public string DesSeobox { get; set; }
        public short? FeatureTag { get; set; }
    }
}