// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class TagRel
    {
        public long TagId { get; set; }
        public long ObjectId { get; set; }
        public byte Type { get; set; }
        public int? SortOrder { get; set; }
    }
}