// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace DongThucVatQuangTri.Models.Entities
{
    public partial class User
    {
        public long Id { get; set; }
        public long CitiesId { get; set; }
        public long CitiesDistrictId { get; set; }
        public string FirstName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Avatar { get; set; }
        public string Gender { get; set; }
        public DateTime? Dob { get; set; }
        public string Address { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public DateTime? LastSigninedTime { get; set; }
        public short IsAdmin { get; set; }
        public short Status { get; set; }
        public string SecretKey { get; set; }
        public string Role { get; set; }

        public int? GroupUserId { get; set; }
    }
}